### PR TITLE
containing the work around the adapter :)

### PR DESCRIPTION
**Pull request by florinpatrascu**

### CODE REVIEW

**Comment by florinpatrascu** [comment]
please use Neo4j.Sips 0.2.x

**Comment by mkompanets** [comment]
awesome

**Comment by florinpatrascu** [comment]
:) cool! I'll update the master at Neo4j.Sips in an hour or so, and publish the new version on Hex as well. Thank you!

**Comment by dotdotdotpaul** [comment]
What exactly needs to be changed in the configuration as a result of this merge?  I've added my graph to the supervisor tree, added the neo4j config parameters to my graph config, updated my neo4j_sips hex to the latest, now I'm getting:

```
** (MatchError) no match of right hand side value: []
    (con_cache) lib/con_cache/registry.ex:18: ConCache.Registry.get/1
    (con_cache) lib/con_cache.ex:143: ConCache.get/2
    lib/callisto/adapters/neo4j.ex:11: Callisto.Adapters.Neo4j.query/1
   ....
```

What am I missing?

**Comment by dotdotdotpaul** [comment]
Strange thing is, I don't get this error when I run my test suite, which exercises some Neo4j queries.  Hrm... :^P

**Comment by dotdotdotpaul** [comment]
Ah.  Something to do with being a mix task.  Grr.

**Comment by florinpatrascu** [comment]
On iPhone, but I can elaborate more later. Sorry for that. However, is this an app like the callisto_demo? if yes, check if it is supervised. Normally when you generate a new app with mix, you'll not have a supervisor, therefore no callback to initialized the adaptor. Can you please paste the Mix.application config?

**Comment by dotdotdotpaul** [comment]
It's a Phoenix app, and I went through the demo you had and tried to find all the places I needed to poke.  My application config is:

```
  def application do
    [mod: {Enki, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :mariaex, :neo4j_sips, :phoenix_haml,
                    :exconstructor, :callisto]]
```

In the run() call for the mix task code, I'm calling:

```
    Application.ensure_all_started(:neo4j_sips)
    Application.ensure_all_started(:callisto)
```

(I had to add the neo4j_sips bit there before), just to be sure, but no dice.  Weird thing is, seems to work in the tests, and in console.  Just doesn't want to work when run as a mix task. 

I also added the supervisor to the project file:

```
      supervisor(Enki.Graph, []),
```

Very odd.

**Comment by dotdotdotpaul** [comment]
Solved.  I needed to ensure_all_started(:enki) (name of the application) not the names of the supervised processes...  My bad.  :)

**Comment by florinpatrascu** [comment]
Ahh, 1st of all if it's a Phoenix web app you need to start Callisto or Nsips as a **worker** :) Please have a look at this: https://github.com/florinpatrascu/movies_elixir_phoenix/blob/master/lib/movies_elixir_phoenix.ex#L13, maybe it helps?! If you're writing a custom Mix.Task then I'll have to poke around a bit, but when I'll get home, in an hour or two.

**Comment by florinpatrascu** [comment]
Cool!!

:)

**Pull request merged**
